services:
  mongodb:
    image: mongo:7
    container_name: watchtower-mongodb
    ports:
      - "27017:27017"
    volumes:
      - watchtower_mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchtower-app
    ports:
      - "5800:5800"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/watchtower
    depends_on:
      - mongodb

volumes:
  watchtower_mongo_data:
